var fs=require("fs"),p=require("path");

function write(f,c){var d=p.dirname("D:/app/easycall/app/android/"+f);if(!fs.existsSync(d))fs.mkdirSync(d,{recursive:true});fs.writeFileSync("D:/app/easycall/app/android/"+f,c,"utf8");console.log("  "+f)}

// Project-level build.gradle
write("build.gradle",'buildscript {\n  ext.kotlin_version="1.7.10"\n  repositories{google();mavenCentral()}\n  dependencies{classpath "com.android.tools.build:gradle:7.3.1";classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"}\n}\nallprojects{repositories{google();mavenCentral()}}\nrootProject.buildDir="../build"\nsubprojects{project.buildDir="${rootProject.buildDir}/${project.name}"}\ntasks.register("clean",Delete){delete rootProject.buildDir}\n');

// settings.gradle
write("settings.gradle",'include ":app"\ndef flutterRoot=localProperties.getProperty("flutter.sdk")\nif(flutterRoot==null)throw new Exception("Flutter SDK not found. Define flutter.sdk in local.properties")\napply from: "$flutterRoot/packages/flutter_tools/gradle/app_plugin_loader.gradle"\n');

// gradle-wrapper.properties
write("gradle/wrapper/gradle-wrapper.properties","distributionBase=GRADLE_USER_HOME\ndistributionPath=wrapper/dists\nzipStoreBase=GRADLE_USER_HOME\nzipStorePath=wrapper/dists\ndistributionUrl=https\\://services.gradle.org/distributions/gradle-7.6-all.zip\n");

// App-level build.gradle
write("app/build.gradle",'plugins{id "com.android.application"}\nandroid{\n  compileSdk 34\n  namespace "com.easycall.app"\n  defaultConfig{\n    applicationId "com.easycall.app"\n    minSdk 21\n    targetSdk 34\n    versionCode 1\n    versionName "1.0.0"\n    multiDexEnabled true\n  }\n  compileOptions{sourceCompatibility JavaVersion.VERSION_1_8;targetCompatibility JavaVersion.VERSION_1_8}\n  buildTypes{release{minifyEnabled false}}\n}\nflutter{source".."}\ndependencies{implementation "androidx.multidex:multidex:2.0.1"}\n');

// AndroidManifest.xml
write("app/src/main/AndroidManifest.xml",'<manifest xmlns:android="http://schemas.android.com/apk/res/android"><uses-permission android:name="android.permission.INTERNET"/><uses-permission android:name="android.permission.CAMERA"/><uses-permission android:name="android.permission.RECORD_AUDIO"/><uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/><uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/><uses-permission android:name="android.permission.FOREGROUND_SERVICE"/><uses-permission android:name="android.permission.WAKE_LOCK"/><application android:label="EasyCall" android:name="io.flutter.app.FlutterApplication" android:usesCleartextTraffic="true"><activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale" android:hardwareAccelerated="true" android:showWhenLocked="true" android:turnScreenOn="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity><service android:name=".EasyCallAccessibilityService" android:exported="true" android:permission="android.permission.BIND_ACCESSIBILITY_SERVICE"><intent-filter><action android:name="android.accessibilityservice.AccessibilityService"/></intent-filter><meta-data android:name="android.accessibilityservice" android:resource="@xml/accessibility_service_config"/></service></application></manifest>');

// res/values/strings.xml
write("app/src/main/res/values/strings.xml",'<?xml version="1.0" encoding="utf-8"?><resources><string name="app_name">EasyCall</string><string name="accessibility_service_desc">EasyCall uses this for remote touch simulation</string></resources>');

// res/values/styles.xml
write("app/src/main/res/values/styles.xml",'<?xml version="1.0" encoding="utf-8"?><resources><style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar"/></resources>');

// res/xml/accessibility_service_config.xml
write("app/src/main/res/xml/accessibility_service_config.xml",'<?xml version="1.0" encoding="utf-8"?><accessibility-service xmlns:android="http://schemas.android.com/apk/res/android" android:accessibilityEventTypes="typeAllMask" android:accessibilityFeedbackType="feedbackGeneric" android:accessibilityFlags="flagDefault|flagRequestTouchExplorationMode" android:canPerformGestures="true" android:canRetrieveWindowContent="true" android:description="@string/accessibility_service_desc" android:notificationTimeout="100"/>');

// MainActivity.java
write("app/src/main/java/com/easycall/app/MainActivity.java",'package com.easycall.app;\nimport android.os.Bundle;\nimport io.flutter.embedding.android.FlutterActivity;\nimport io.flutter.embedding.engine.FlutterEngine;\nimport io.flutter.plugin.common.MethodChannel;\npublic class MainActivity extends FlutterActivity {\n  private static final String CHANNEL="com.easycall.app/accessibility";\n  private static final String CHANNEL_REMOTE="com.easycall.app/remote";\n  @Override public void configureFlutterEngine(FlutterEngine e){\n    super.configureFlutterEngine(e);\n    new MethodChannel(e.getDartExecutor().getBinaryMessenger(),CHANNEL).setMethodCallHandler((c,r)->{\n      EasyCallAccessibilityService s=EasyCallAccessibilityService.getInstance();\n      switch(c.method){\n        case "isEnabled":r.success(s!=null);break;\n        case "tap":{double x=c.argument("x");double y=c.argument("y");r.success(s!=null&&s.simulateTap((float)x,(float)y));break;}\n        case "swipe":{double x1=c.argument("x1"),y1=c.argument("y1"),x2=c.argument("x2"),y2=c.argument("y2");int d=c.argument("duration");r.success(s!=null&&s.simulateSwipe((float)x1,(float)y1,(float)x2,(float)y2,d));break;}\n        case "pressBack":r.success(s!=null&&s.pressBack());break;\n        case "pressHome":r.success(s!=null&&s.pressHome());break;\n        default:r.notImplemented();\n      }\n    });\n    new MethodChannel(e.getDartExecutor().getBinaryMessenger(),CHANNEL_REMOTE).setMethodCallHandler((c,r)->{\n      switch(c.method){\n        case "playVideo":{String url=c.argument("url");if(url!=null){android.content.Intent i=new android.content.Intent(android.content.Intent.ACTION_VIEW);i.setData(android.net.Uri.parse(url));i.addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK);startActivity(i);r.success(true);}else r.error("NO_URL","",null);break;}\n        case "startForeground":{android.content.Intent i=new android.content.Intent(this,EasyCallForegroundService.class);if(android.os.Build.VERSION.SDK_INT>=android.os.Build.VERSION_CODES.O)startForegroundService(i);else startService(i);r.success(true);break;}\n        default:r.notImplemented();\n      }\n    });\n  }\n}\n');

// EasyCallAccessibilityService.java
write("app/src/main/java/com/easycall/app/EasyCallAccessibilityService.java",'package com.easycall.app;\nimport android.accessibilityservice.AccessibilityService;\nimport android.accessibilityservice.GestureDescription;\nimport android.graphics.Path;\nimport android.os.Build;\nimport android.view.accessibility.AccessibilityNodeInfo;\npublic class EasyCallAccessibilityService extends AccessibilityService {\n  private static EasyCallAccessibilityService instance;\n  @Override public void onAccessibilityEvent(android.view.accessibility.AccessibilityEvent e){}\n  @Override public void onInterrupt(){}\n  @Override public void onCreate(){super.onCreate();instance=this;}\n  @Override public void onDestroy(){super.onDestroy();instance=null;}\n  public static EasyCallAccessibilityService getInstance(){return instance;}\n  public boolean simulateTap(float x,float y){if(Build.VERSION.SDK_INT<24)return false;Path p=new Path();p.moveTo(x,y);GestureDescription.StrokeDescription s=new GestureDescription.StrokeDescription(p,0,100);GestureDescription.Builder b=new GestureDescription.Builder();b.addStroke(s);return dispatchGesture(b.build(),null,null);}\n  public boolean simulateSwipe(float x1,float y1,float x2,float y2,int ms){if(Build.VERSION.SDK_INT<24)return false;Path p=new Path();p.moveTo(x1,y1);p.lineTo(x2,y2);GestureDescription.StrokeDescription s=new GestureDescription.StrokeDescription(p,0,ms);GestureDescription.Builder b=new GestureDescription.Builder();b.addStroke(s);return dispatchGesture(b.build(),null,null);}\n  public boolean pressBack(){return performGlobalAction(GLOBAL_ACTION_BACK);}\n  public boolean pressHome(){return performGlobalAction(GLOBAL_ACTION_HOME);}\n}\n');

// ForegroundService.java
write("app/src/main/java/com/easycall/app/EasyCallForegroundService.java",'package com.easycall.app;\nimport android.app.Notification;\nimport android.app.NotificationChannel;\nimport android.app.NotificationManager;\nimport android.app.Service;\nimport android.content.Intent;\nimport android.os.Build;\nimport android.os.IBinder;\npublic class EasyCallForegroundService extends Service {\n  private static final String CHANNEL_ID="easycall_online";\n  private static final int NOTIFY_ID=1001;\n  @Override public void onCreate(){super.onCreate();if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){NotificationChannel c=new NotificationChannel(CHANNEL_ID,"Online",NotificationManager.IMPORTANCE_LOW);c.setDescription("Shows EasyCall online status");NotificationManager m=getSystemService(NotificationManager.class);if(m!=null)m.createNotificationChannel(c);}}\n  @Override public int onStartCommand(Intent i,int f,int sid){Notification n=new Notification.Builder(this,CHANNEL_ID).setContentTitle("EasyCall").setContentText("Online - ready for calls and remote help").setSmallIcon(android.R.drawable.ic_menu_call).setOngoing(true).build();startForeground(NOTIFY_ID,n);return START_STICKY;}\n  @Override public IBinder onBind(Intent i){return null;}\n}\n');

// AudioUtils.java
write("app/src/main/java/com/easycall/app/AudioUtils.java",'package com.easycall.app;\nimport android.content.Context;\nimport android.media.AudioManager;\npublic class AudioUtils {\n  public static void adjustVolume(Context c,boolean up){AudioManager a=(AudioManager)c.getSystemService(Context.AUDIO_SERVICE);if(a!=null)a.adjustStreamVolume(AudioManager.STREAM_MUSIC,up?AudioManager.ADJUST_RAISE:AudioManager.ADJUST_LOWER,AudioManager.FLAG_SHOW_UI);}\n}\n');

console.log("\\nAll files created!");
