name: easycall
description: EasyCall - 简单易用的视频通话和远程协助应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_webrtc: ^0.9.52
  socket_io_client: ^2.0.3+1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  permission_handler: ^11.1.0
  wakelock_plus: ^1.1.4
  screen_brightness: ^0.2.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
